### PR TITLE
ENH: For str, compute interval it could be rounded/truncated from

### PR DESCRIPTION
**Pull request by Leengit**
Add two subroutines, `_interval_rounding_to_str` and `_interval_truncating_to_str`.  For example for the input string `"3.14"`, the first returns a pair of `fractions.Fraction` objects, exactly equal to `3.135` and `3.145`.  The second returns a pair of `fractions.Fraction` objects, exactly equal to `3.14` and `3.15`.

These can be subroutines for one or more public methods.  A subroutine would be used as the first step and then a call to `_simplest_in_interval` would make use of the interval from the first step to compute a simple fraction; much as in the current implementation of `simplest_from_float`.  These public routines are not part of this pull request.  I leave those API decisions to @mdickinson to direct.

### CODE REVIEW

**Comment by mdickinson** [comment]
Hi @Leengit. Thank you for the contribution! I'm afraid that this isn't a direction I want to take `simplefractions` in, but if you want to create your own package I'd be interested to see the results.

BTW, I think there's a more direct way to compute these endpoints, which is to use the `decimal` module. As an example, after doing `from decimal import Decimal` and `from fractions import Fraction`:

```python
>>> s = "3.1799e2"  # example input string
>>> d = Decimal(s)  # convert to Decimal
>>> *_, exponent = d.as_tuple()  # extract exponent of the least significant digit
>>> eps = Decimal(f"0.5e{exponent}") 
>>> Fraction(d-eps), Fraction(d+eps)
(Fraction(63597, 200), Fraction(63599, 200))
```

**Comment by mdickinson** [comment]
Hmm. That's not quite right, since `d - eps` and `d + eps` are computed in the `decimal` domain, and in cases of a very large number of significant digits will end up being rounded. Better to do the actual arithmetic in Fraction-land. Here's an improved version:

```python
>>> s = "3.141"
>>> f = Fraction(s)
>>> *_, exponent = Decimal(s).as_tuple()
>>> eps = Fraction(f"0.5e{exponent}")
>>> f-eps, f+eps
(Fraction(6281, 2000), Fraction(6283, 2000))
```

**Comment by Leengit** [comment]
I want to add that I very much appreciate this `simplefractions` package.  It has useful functionality and is well written.  Those are the reasons that I suggested this pull request.  It is my fear that creating my own package would have to duplicate much of the good effort here.

And, in case it isn't obvious ... if you ever want to incorporate any aspect of my pull request (with or without your approach via `decimals`), please do not hesitate to do so -- there is no need to check with me or credit me, etc.

**Comment by Leengit** [comment]
If you know of an approach similar to your `decimals` approach for handling binary, octal, and hexadecimal too, I'd like to see it.  The best I can come up with is something along the lines of following.  Each section differs on which prefix it is looking for ("", "0x", "0o", "0b") and which trailing digit it adds ("5", "8", "4", "1").
```python
    # If `target` is positive then we can figure the right end of the rounding interval by attaching a "5"
    # suffix to the mantissa.  If the mantissa does not include a decimal point then append a decimal point
    # before appending the "5".
    right = target
    # Decimal (or use the `decimals` package)
    right = re.sub(r"^([+-]?[0-9_]*)(\.([0-9_]*))?([eE][+-]?[0-9_]+)?$", r"\g<1>.\g<3>5\g<4>", right)
    # Hexadecimal
    right = re.sub(r"^0x([+-]?[0-9_]*)(\.([0-9_]*))?([eE][+-]?[0-9_]+)?$", r"0x\g<1>.\g<3>8\g<4>", right)
    # Octal
    right = re.sub(r"^0o([+-]?[0-9_]*)(\.([0-9_]*))?([eE][+-]?[0-9_]+)?$", r"0o\g<1>.\g<3>4\g<4>", right)
    # Binary
    right = re.sub(r"^0b([+-]?[0-9_]*)(\.([0-9_]*))?([eE][+-]?[0-9_]+)?$", r"0b\g<1>.\g<3>1\g<4>", right)
    if right == target:
        raise ValueError(f"target ({target}) not recognized as a number")
```

**Pull request closed without merging**
